Reports datetime input
Our-Dream-Company/Your_finance_helper pull request #10
Opened 2021-11-01 21:29 UTC by scad89

created a statement by dates in main_page and reports, made inquiries from the 1st of the current month to today

2021-11-01 21:42 UTC, Niccolum requested changes

2021-11-01 21:42 UTC, Niccolum commented on your_finance_helper/main_page/templates/main_page/layout.html
> +<!--   <link href="{% static 'reports/js/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet">
Законченные строки можешь удалить

2021-11-01 21:42 UTC, Niccolum commented on your_finance_helper/main_page/views.py
> +                date__range=[datetime.now().replace(day=1).date(),
Рэйндж всегда фиксированный?

2021-11-01 21:42 UTC, Niccolum commented on your_finance_helper/main_page/views.py
> +        def split_queryset(data):
Повтор функции из другой вьюхи

2021-11-01 21:42 UTC, Niccolum commented on your_finance_helper/reports/templates/reports/detailed_current_financial_results.html
> +<!--
Удаляй законченный код.

2021-11-01 21:42 UTC, Niccolum commented on your_finance_helper/reports/views.py
> +            date__range=[datetime.now().replace(day=1).date(),
Опять фиксированный рейндж?

2021-11-01 21:53 UTC, scad89 commented on your_finance_helper/main_page/templates/main_page/layout.html
> +<!--   <link href="{% static 'reports/js/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet">
Готово

2021-11-01 21:54 UTC, scad89 commented on your_finance_helper/main_page/views.py
> +                date__range=[datetime.now().replace(day=1).date(),
Да. Я так и планировал сделать изначально, чтобы получать данные операций за текущий месяц.

2021-11-01 21:54 UTC, scad89 commented on your_finance_helper/main_page/views.py
> +        def split_queryset(data):
Создал модуль, закоммитил.

2021-11-01 21:55 UTC, scad89 commented on your_finance_helper/reports/templates/reports/detailed_current_financial_results.html
> +<!--
Выполнено

2021-11-01 21:55 UTC, scad89 commented on your_finance_helper/reports/views.py
> +            date__range=[datetime.now().replace(day=1).date(),
Да, текущего месяца

2021-11-01 21:56 UTC, Niccolum commented on your_finance_helper/reports/views.py
> +            date__range=[datetime.now().replace(day=1).date(),
Но зачем фиксировать явно, если можно задать его по умолчанию и переопределять в форме?

2021-11-01 21:56 UTC, Niccolum commented on your_finance_helper/main_page/views.py
> +                date__range=[datetime.now().replace(day=1).date(),
Ответил в другом месте

2021-11-01 21:57 UTC, scad89 commented on your_finance_helper/reports/views.py
> +            date__range=[datetime.now().replace(day=1).date(),
Мне показалось так удобно

2021-11-16 13:31 UTC, Niccolum commented on your_finance_helper/main_page/urls.py
> +    path('add_new_name', views.AddNewNameView.as_view(), name='add_new_name'),
Можешь более понятный нейминг сделать? Неясно, что за new name

2021-11-16 13:31 UTC, Niccolum commented on your_finance_helper/main_page/views.py
> +        start_date = datetime.now().replace(day=1).date()
Почему это всё ещё тут?

2021-11-16 13:31 UTC, Niccolum commented on your_finance_helper/reports/views.py
> +class DetailedCurrentFinancialResultsView(View):
Чем это отличается от вьюхи IndexView(View)?

2021-11-16 13:38 UTC, scad89 commented on your_finance_helper/main_page/urls.py
> +    path('add_new_name', views.AddNewNameView.as_view(), name='add_new_name'),
Это возможно добавлять новое наименование. Как add_new_category(добавить новую категорию) и add_new_section(секцию)

2021-11-16 13:39 UTC, scad89 commented on your_finance_helper/main_page/views.py
> +        start_date = datetime.now().replace(day=1).date()
Если без этого, то мне пишет ошибку local variable 'start_date' referenced before assignment. То есть эта переменная была не объявлена

2021-11-16 13:41 UTC, scad89 commented on your_finance_helper/reports/views.py
> +class DetailedCurrentFinancialResultsView(View):
Данными в запросе. В IndexView я тяну определённый и потом декомпозирую на словари для необходимого вывода, а тут я просто вытягиваю все данные и вывожу, так как это подробный отчёт.

2021-11-16 14:04 UTC, Niccolum commented on your_finance_helper/main_page/views.py
> +        start_date = datetime.now().replace(day=1).date()
Это значит у тебя невалидная форма? У тебя всё должно быть внутри if form.is_valid()

2021-11-22 16:43 UTC, Niccolum requested changes

2021-11-22 16:43 UTC, Niccolum commented on your_finance_helper/main_page/forms.py
> +                'placeholder': 'Name'
Мне казалось мы обсуждали нэйминг

2021-11-22 16:43 UTC, Niccolum commented on your_finance_helper/main_page/urls.py
> +    path('add_new_name', views.AddNewNameView.as_view(), name='add_new_name'),
Всё ещё старый нейминг?

2021-11-22 16:43 UTC, Niccolum commented on your_finance_helper/reports/forms.py
> +YEAR_CHOICES = tuple([i for i in range(2010, 2041)])
tuple(i for i in range(2010, 2041))

2021-11-22 16:43 UTC, Niccolum commented on your_finance_helper/tests/reports/test_views_reports.py
> +     'reports/detailed_current_financial_results.html'),    # transaction_update и transaction_delete протестировать
Коммент актуален?

2021-11-22 16:43 UTC, Niccolum commented on your_finance_helper/tests/reports/test_views_reports.py
> +# @pytest.mark.parametrize('url_form, form', [
Почему ошибка? Не хочешь попробовать разобраться?

2021-11-23 13:07 UTC, merged